version: '3'

services:
  postgres:
    image: postgres:12-alpine
    container_name: $DB_DATABASE
    ports:
      - "$DB_PORT:5432"
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
    volumes:
      - gorm_volume:/var/lib/postgresql/data

volumes:
  gorm_volume:
