definitions:
  controllers.Login.loginRequestBody:
    properties:
      email:
        type: string
      organization_name:
        type: string
      password:
        type: string
    required:
    - email
    - organization_name
    - password
    type: object
  controllers.Register.registerRequestBody:
    properties:
      email:
        type: string
      organization_name:
        type: string
      password:
        type: string
    required:
    - email
    - organization_name
    - password
    type: object
  controllers.organizationBody:
    properties:
      aliasName:
        type: string
      description:
        type: string
      establishmentDate:
        type: string
      name:
        type: string
    type: object
  controllers.projectBody:
    properties:
      currentSprint:
        type: integer
      description:
        type: string
      name:
        type: string
      repoURL:
        type: string
      startAt:
        type: string
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.Agent:
    properties:
      apitoken:
        type: string
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      environment:
        $ref: '#/definitions/models.Environment'
      environmentID:
        type: integer
      id:
        type: integer
      name:
        type: string
      projectID:
        type: integer
      stage:
        $ref: '#/definitions/models.Stage'
      stageID:
        type: integer
      updatedAt:
        type: string
    type: object
  models.Environment:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      name:
        type: string
      project:
        $ref: '#/definitions/models.Project'
      projectID:
        type: integer
      updatedAt:
        type: string
    type: object
  models.Parameter:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      description:
        type: string
      environment:
        $ref: '#/definitions/models.Environment'
      environmentID:
        type: integer
      id:
        type: integer
      name:
        type: string
      stage:
        $ref: '#/definitions/models.Stage'
      stageID:
        type: integer
      updatedAt:
        type: string
      value:
        type: string
    type: object
  models.Project:
    properties:
      agent:
        items:
          $ref: '#/definitions/models.Agent'
        type: array
      createdAt:
        type: string
      currentSprint:
        type: integer
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      description:
        type: string
      environments:
        items:
          $ref: '#/definitions/models.Environment'
        type: array
      id:
        type: integer
      name:
        type: string
      organizationID:
        type: integer
      repoURL:
        type: string
      stages:
        items:
          $ref: '#/definitions/models.Stage'
        type: array
      startAt:
        type: string
      updatedAt:
        type: string
      versions:
        items:
          $ref: '#/definitions/models.Version'
        type: array
    type: object
  models.Stage:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      name:
        type: string
      project:
        $ref: '#/definitions/models.Project'
      projectID:
        type: integer
      updatedAt:
        type: string
    type: object
  models.Version:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      description:
        type: string
      id:
        type: integer
      number:
        type: string
      parameters:
        items:
          $ref: '#/definitions/models.Parameter'
        type: array
      projectID:
        type: integer
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Login a user
      parameters:
      - description: User login request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.Login.loginRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "User logged in successfully", "user": {email:
            "email", organization_id: "organization_id"}}'
          schema:
            type: string
        "400":
          description: '{"error": "Bad request"}'
          schema:
            type: string
        "401":
          description: '{"error": "Unauthorized"}'
          schema:
            type: string
        "500":
          description: '{"error": "Failed to login user"}'
          schema:
            type: string
      summary: Login a user
      tags:
      - Auth
  /api/v1/auth/logout:
    post:
      consumes:
      - application/json
      description: Logout a user
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "User logged out successfully"}'
          schema:
            type: string
        "400":
          description: '{"error": "Bad request"}'
          schema:
            type: string
        "500":
          description: '{"error": "Failed to logout user"}'
          schema:
            type: string
      summary: Logout a user
      tags:
      - Auth
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User registration request
        in: body
        name: Creadentials
        required: true
        schema:
          $ref: '#/definitions/controllers.Register.registerRequestBody'
      produces:
      - application/json
      responses:
        "201":
          description: "{\"message\": \"User registered successfully\", \"user\":
            {email: \"\temail\", organization_id: \"organization_id\"}}"
          schema:
            type: string
        "400":
          description: '{"error": "Bad request"}'
          schema:
            type: string
        "500":
          description: '{"error": "Failed to register user"}'
          schema:
            type: string
      summary: Register a new user
      tags:
      - Auth
  /api/v1/auth/validate:
    get:
      consumes:
      - application/json
      description: Validate a user
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "User logged in successfully"}'
          schema:
            type: string
        "400":
          description: '{"error": "Bad request"}'
          schema:
            type: string
        "500":
          description: '{"error": "Failed to validate user"}'
          schema:
            type: string
      summary: Validate a user
      tags:
      - Auth
  /api/v1/organization/:
    get:
      consumes:
      - application/json
      description: Get organization information
      produces:
      - application/json
      responses:
        "200":
          description: '{"organizations": "organizations"}'
          schema:
            type: string
        "400":
          description: '{"error": "Bad request"}'
          schema:
            type: string
        "500":
          description: '{"error": "Failed to get organization"}'
          schema:
            type: string
      summary: Get organization information
      tags:
      - Organization
    put:
      consumes:
      - application/json
      description: Update organization information
      parameters:
      - description: Organization
        in: body
        name: Organization
        required: true
        schema:
          $ref: '#/definitions/controllers.organizationBody'
      produces:
      - application/json
      responses:
        "200":
          description: '{"organizations": "organizations"}'
          schema:
            type: string
        "400":
          description: '{"error": "Bad request"}'
          schema:
            type: string
        "500":
          description: '{"error": "Failed to get organization"}'
          schema:
            type: string
      summary: Update organization information
      tags:
      - Organization
  /api/v1/organization/projects:
    get:
      consumes:
      - application/json
      description: List projects
      produces:
      - application/json
      responses:
        "200":
          description: '{"projects": "projects"}'
          schema:
            type: string
        "400":
          description: '{"error": "Bad request"}'
          schema:
            type: string
        "500":
          description: '{"error": "Failed to list projects"}'
          schema:
            type: string
      summary: List projects
      tags:
      - Organization
    post:
      consumes:
      - application/json
      description: Create new project for organization
      parameters:
      - description: Project
        in: body
        name: Project
        required: true
        schema:
          $ref: '#/definitions/controllers.projectBody'
      produces:
      - application/json
      responses:
        "200":
          description: '{"project": "project"}'
          schema:
            type: string
        "400":
          description: '{"error": "Bad request"}'
          schema:
            type: string
        "500":
          description: '{"error": "Failed to create project"}'
          schema:
            type: string
      summary: Create new project
      tags:
      - Organization
  /api/v1/organization/projects/{project_id}:
    delete:
      consumes:
      - application/json
      description: Delete project
      parameters:
      - description: Project ID
        in: path
        name: project_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Project deleted"}'
          schema:
            type: string
        "400":
          description: '{"error": "Bad request"}'
          schema:
            type: string
        "500":
          description: '{"error": "Failed to delete project"}'
          schema:
            type: string
      summary: Delete project
      tags:
      - Organization
  /api/v1/project/{project_id}/agent:
    get:
      consumes:
      - application/json
      description: Get agents of project
      parameters:
      - description: Project ID
        in: path
        name: project_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Agent'
            type: array
        "400":
          description: '{"error": "Bad request"}'
          schema:
            type: string
        "500":
          description: '{"error": "Failed to get agents"}'
          schema:
            type: string
      summary: Get agents of project
      tags:
      - Project Detail / Agent
    post:
      consumes:
      - application/json
      description: Create new agent
      parameters:
      - description: Project ID
        in: path
        name: project_id
        required: true
        type: integer
      - description: Agent
        in: body
        name: Agent
        required: true
        schema:
          $ref: '#/definitions/models.Agent'
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Agent created"}'
          schema:
            type: string
        "400":
          description: '{"error": "Bad request"}'
          schema:
            type: string
        "500":
          description: '{"error": "Failed to create agent"}'
          schema:
            type: string
      summary: Create new agent
      tags:
      - Project Detail / Agent
  /api/v1/project/{project_id}/overview:
    get:
      consumes:
      - application/json
      description: Get project overview
      parameters:
      - description: Project ID
        in: path
        name: project_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"project": "project"}'
          schema:
            type: string
        "400":
          description: '{"error": "Bad request"}'
          schema:
            type: string
        "500":
          description: '{"error": "Failed to get project detail"}'
          schema:
            type: string
      summary: Get project overview
      tags:
      - Project Detail / Overview
    put:
      consumes:
      - application/json
      description: Update project information
      parameters:
      - description: Project ID
        in: path
        name: project_id
        required: true
        type: string
      - description: Project
        in: body
        name: Project
        required: true
        schema:
          $ref: '#/definitions/controllers.projectBody'
      produces:
      - application/json
      responses:
        "200":
          description: '{"project": "project"}'
          schema:
            type: string
        "400":
          description: '{"error": "Bad request"}'
          schema:
            type: string
        "500":
          description: '{"error": "Failed to update project"}'
          schema:
            type: string
      summary: Update project information
      tags:
      - Project Detail / Overview
swagger: "2.0"
